
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-server:3306/WEBUSERDB?autoreconnect = true
    username: root
    password: mandal01
  application:
    name: user-search-delete-service


server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
    instance-id: ${spring.application.name}:${random.value}
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://discovery-server:8761/eureka/
    availability-zones:
      region1: zone1